---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<p id = "cat">Category</p>
<strong><p id = "title">Data Overview</p></strong>
<br><br>
<p id="portada">La Portada</p>
<br><br>
<p id="desc">Have you ever read through power rankings, mock-drafts, or projected standings, and wondered: "does anyone actually ever look back to see how they did?"<br><br>Perhaps it's just me that thinks about this. After all, if they are successful clickbait, even after the predictions/rankings/etc. failed, maybe it doesn't matter after all. <br><br> In any case, this isn't about failing, or being successful: these are arbitrarily assigned player performance grades! And this is just a little bit of fun.<br><br>This is trying to see if we can find anything interesting in a year's worth of player performance grades, which won't probably tell us anything new about the players - but if anything - more about the authors.
</p>


<style>
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@300;500&display=swap');

#cat{
  margin: auto;
  text-align: center;
  font-size: 20px;
  font-family: 'Roboto', sans-serif;
}

#title{
  margin: auto;
  text-align: center;
  font-size: 40px;
  font-family: 'Roboto', sans-serif;
}

#desc{
  font-size: 20px;
  font-family: 'Roboto', sans-serif;
}

#portada{
  margin: auto;
  text-align: center;
  font-family: 'Zilla Slab', serif;
  font-size: 30px;
  color: #2553CC;
}

</style>
